/**
 * scraper.js
 * Team-BHP bulk scraper with AI-powered batch categorisation via OpenRouter.
 *
 * pnpm packages required:
 *   pnpm add puppeteer axios zod
 *   (node built-ins used: fs, path, crypto — no install needed)
 */

const puppeteer = require('puppeteer');
const axios     = require('axios');
const fs        = require('fs');
const path      = require('path');
const crypto    = require('crypto');



// ═══════════════════════════════════════════════════════════════════════════════
//  CAR LIST
//  Priority: load from trims_data.json (generated by fetch_trims.js) if it
//  exists, otherwise exits with a clear error — run fetch_trims.js first.
// ═══════════════════════════════════════════════════════════════════════════════
const TRIMS_DATA_FILE = path.join(__dirname, 'trims_data.json');

function loadCarList() {
    if (fs.existsSync(TRIMS_DATA_FILE)) {
        try {
            const data = JSON.parse(fs.readFileSync(TRIMS_DATA_FILE, 'utf-8'));
            const list = data.carList ?? [];
            if (list.length > 0) {
                console.log(`[init] ✅ Loaded ${list.length} cars from trims_data.json`);
                return list;
            }
        } catch (e) {
            console.error(`[init] ❌ Failed to parse trims_data.json: ${e.message}`);
        }
    }
    console.error('[init] ❌ trims_data.json not found or empty. Run fetch_trims.js first.');
    process.exit(1);
}

const CAR_LIST = loadCarList();

// ═══════════════════════════════════════════════════════════════════════════════
//  DELAYS
// ═══════════════════════════════════════════════════════════════════════════════
const DELAY_AFTER_SEARCH_LOAD    = 3000;
const DELAY_AFTER_REVIEWS_CLICK  = 6000;
const DELAY_AFTER_PAGE_CLICK     = 5000;
const DELAY_BETWEEN_THREADS      = 3000;
const DELAY_BETWEEN_THREAD_PAGES = 2000;
const DELAY_BETWEEN_CARS         = 5000;

const OUTPUT_DIR = path.join(__dirname, 'scraped_data');

const GLOBAL_REVIEWS_FILE = path.join(OUTPUT_DIR, 'all_reviews.json');
const GLOBAL_QUEUE_FILE   = path.join(OUTPUT_DIR, 'all_queue.json');
const GLOBAL_MONGO_FILE   = path.join(OUTPUT_DIR, 'all_mongo.json');

// ═══════════════════════════════════════════════════════════════════════════════
//  UTILITIES
// ═══════════════════════════════════════════════════════════════════════════════
const DELAY = ms => new Promise(r => setTimeout(r, ms));
function log(msg) { console.log(`[${new Date().toLocaleTimeString()}] ${msg}`); }

// ═══════════════════════════════════════════════════════════════════════════════
//  PROGRESS
// ═══════════════════════════════════════════════════════════════════════════════
const PROGRESS_FILE = path.join(OUTPUT_DIR, 'progress.json');
function loadProgress() { return fs.existsSync(PROGRESS_FILE) ? JSON.parse(fs.readFileSync(PROGRESS_FILE, 'utf-8')) : { lastCompletedCarIndex: -1 }; }
function saveProgress(i) { fs.writeFileSync(PROGRESS_FILE, JSON.stringify({ lastCompletedCarIndex: i }, null, 2), 'utf-8'); }

// ═══════════════════════════════════════════════════════════════════════════════
//  MONGO DOC BUILDER
// ═══════════════════════════════════════════════════════════════════════════════
function makeObjectId(seed) { return crypto.createHash('md5').update(seed).digest('hex').substring(0, 24); }

function guessCategoryFromUrl(url) {
    if (!url) return null;
    const lower = url.toLowerCase();
    if (lower.includes('ownership-review')) return 'OwnershipReview';
    if (lower.includes('vs-') || lower.includes('-vs')) return 'Comparison';
    if (lower.includes('issue') || lower.includes('problem')) return 'Issue/Problem';
    return null;
}

function toMongoDoc({ post, threadUrl, brandSlug, modelSlug, category, carEntry }) {
    // Determine object IDs: favor the precise IDs from trims_data if available
    const brandOid   = carEntry?._brandId || makeObjectId(`brand_${brandSlug}`);
    const modelOid   = carEntry?._modelId || makeObjectId(`model_${modelSlug}`);
    const reviewOid  = makeObjectId(`${threadUrl}_${post.postNumber}_${post.author.name}`);
    const cwReviewId = Math.abs(parseInt(crypto.createHash('md5').update(reviewOid).digest('hex').substring(0, 8), 16));
    const ratingMatch   = post.content.match(/(\d)\s*\/\s*10|\brat(?:ing|ed)[^\d]*(\d)/i);
    const overallRating = ratingMatch ? parseInt(ratingMatch[1] || ratingMatch[2]) : 0;
    
    // Check if the URL overtly identifies the category, else use fallback provided
    const urlGuessedCategory = guessCategoryFromUrl(threadUrl);
    const finalCategory = urlGuessedCategory || category || 'pending_ai';
    
    const doc = {
        _id:          { $oid: reviewOid },
        cwReviewId,
        __v:          0,
        brandId:      { $oid: brandOid },
        createdAt:    { $date: new Date().toISOString() },
        customerInfo: { userName: post.author.name || '', userEmail: '', userlocation: post.author.location || '' },
        description:  post.content,
        downvotes:    0,
        entryDate:    post.postDate || '',
        modelId:      { $oid: modelOid },
        overallRating,
        ratingParams: { designAndStyling: 0, comfortAndSpace: 0, performance: 0, valueForMoney: 0, featuresAndTechnology: 0, afterSalesCostAndExperience: 0 },
        title:        threadUrl.split('/').pop().replace('.html', '').replace(/-/g, ' '),
        updatedAt:    { $date: new Date().toISOString() },
        upvotes:      post.thanksCount || 0,
        userUploadedImages: [],
        status:       'pending',
        category:     finalCategory,
        _meta: { threadUrl, postNumber: post.postNumber, authorRank: post.author.rank, authorPosts: post.author.postsCount, authorJoined: post.author.joinDate, source: 'team-bhp' },
    };

    if (carEntry?._trimId) {
        doc.trimId = { $oid: carEntry._trimId };
    }

    return doc;
}

// ═══════════════════════════════════════════════════════════════════════════════
//  SCRAPING HELPERS  (unchanged from original)
// ═══════════════════════════════════════════════════════════════════════════════
function normalizeThreadUrl(href) { return href.split('#')[0].replace(/-\d+\.html$/, '.html'); }

async function waitForGSCResults(page, timeoutMs = 10000) {
    try { await page.waitForFunction(() => document.querySelectorAll('.gsc-result, .gs-result').length > 0, { timeout: timeoutMs }); return true; } catch (_) { return false; }
}
async function waitForGSCPage(page, pageNum, timeoutMs = 10000) {
    try { await page.waitForFunction((n) => { const a = document.querySelector('.gsc-cursor-current-page'); return a && a.textContent.trim() === String(n); }, { timeout: timeoutMs }, pageNum); await DELAY(1500); return true; } catch (_) { return false; }
}
async function grabCurrentPageLinks(page) {
    return page.evaluate(() =>
        Array.from(document.querySelectorAll('a.gs-title, .gsc-webResult a[href], .gs-result a[href]'))
            .map(a => a.href || '').filter(h => h.includes('team-bhp.com/forum') && h.includes('.html') && !h.includes('/member') && !h.includes('/search.php') && !h.includes('/galleryV2'))
    );
}

async function collectReviewLinks(page, query) {
    log(`\n🔍 Searching for: "${query}"`);
    const searchUrl = 'https://www.team-bhp.com/search.php?cx=partner-pub-8422315737402856%3Azcmboq-gw8i&cof=FORID%3A9&ie=ISO-8859-1&sa=&q=' + encodeURIComponent(query);
    await page.goto(searchUrl, { waitUntil: 'domcontentloaded', timeout: 60000 });
    await DELAY(DELAY_AFTER_SEARCH_LOAD);
    log('Clicking "Reviews" tab...');
    const clicked = await page.evaluate(() => { const el = Array.from(document.querySelectorAll('a, div, span, li, td')).find(e => e.innerText && e.innerText.trim() === 'Reviews'); if (el) { el.click(); return true; } return false; });
    if (clicked) { log(`✔ Reviews tab clicked`); await DELAY(DELAY_AFTER_REVIEWS_CLICK); await waitForGSCResults(page, 8000); }
    else { log('⚠️  Reviews tab not found'); await DELAY(3000); }
    const totalPages = await page.evaluate(() => document.querySelectorAll('.gsc-cursor-page').length);
    log(`Found ${totalPages} search result pages`);
    const seenRoots = new Set();
    (await grabCurrentPageLinks(page)).forEach(h => seenRoots.add(normalizeThreadUrl(h)));
    for (let p = 2; p <= totalPages; p++) {
        const didClick = await page.evaluate((n) => { const btn = Array.from(document.querySelectorAll('.gsc-cursor-page')).find(el => el.textContent.trim() === String(n)); if (btn) { btn.click(); return true; } return false; }, p);
        if (!didClick) break;
        const loaded = await waitForGSCPage(page, p, 10000);
        if (!loaded) await DELAY(DELAY_AFTER_PAGE_CLICK);
        (await grabCurrentPageLinks(page)).forEach(h => seenRoots.add(normalizeThreadUrl(h)));
        log(`  ✔ Page ${p} | ${seenRoots.size} total links`);
    }
    const unique = [...seenRoots];
    log(`📋 ${unique.length} unique threads found`);
    return unique;
}

async function scrapeThreadPage(page) {
    return page.evaluate(() => {
        const results = [];
        document.querySelectorAll('table[id^="post"]').forEach(post => {
            const userMenu = post.querySelector('div[id^="postmenu_"]');
            const userName = userMenu ? userMenu.innerText.trim() : 'Unknown';
            const cell = post.querySelector('td.alt2');
            let userRank = '', joinDate = '', location = '', postsCount = '';
            if (cell) {
                const divs = cell.querySelectorAll('div.smallfont');
                if (divs.length > 0) userRank = divs[0].innerText.trim();
                const text = cell.innerText;
                const m1 = text.match(/Join Date:\s*(.*)/); const m2 = text.match(/Location:\s*(.*)/); const m3 = text.match(/Posts:\s*(.*)/);
                if (m1) joinDate = m1[1].trim(); if (m2) location = m2[1].trim(); if (m3) postsCount = m3[1].trim();
            }
            const dateEl = post.querySelector('td.thead');
            let postDate = '', postNumber = '';
            if (dateEl) { const parts = dateEl.innerText.trim().split('#'); postDate = parts[0].trim(); postNumber = parts[1] ? '#' + parts[1].trim() : ''; }
            const msgEl = post.querySelector('div[id^="post_message_"]');
            const content = msgEl ? msgEl.innerText.trim() : '';
            let thanksCount = 0;
            const thanksCell = post.querySelector('td[id^="td_thanks_"], .thanks_postbit, [id^="thanks_for_post"]');
            if (thanksCell) { const m = thanksCell.innerText.match(/\((\d+)\)/); if (m) thanksCount = parseInt(m[1], 10); }
            if (!thanksCount) { const m = (post.innerText || '').match(/\((\d+)\)\s*Thanks/i); if (m) thanksCount = parseInt(m[1], 10); }
            results.push({ postNumber, postDate, author: { name: userName, rank: userRank, joinDate, location, postsCount }, content, thanksCount });
        });
        return results;
    });
}

async function scrapeThread(page, threadUrl, onPageScraped) {
    log(`  Opening: ${threadUrl}`);
    let currentUrl = threadUrl, allPosts = [], pageNum = 1;
    const pageUrls = [];
    while (currentUrl) {
        log(`    → Page ${pageNum}: ${currentUrl}`);
        pageUrls.push(currentUrl);
        try { await page.goto(currentUrl, { waitUntil: 'domcontentloaded', timeout: 60000 }); await page.waitForSelector('table[id^="post"]', { timeout: 15000 }); }
        catch (e) { log(`    ⚠️  Could not load — skipping. (${e.message})`); break; }
        const posts = await scrapeThreadPage(page);
        log(`    ✔ ${posts.length} posts`);
        
        if (onPageScraped && posts.length > 0) {
            await onPageScraped(posts);
        }
        
        allPosts = allPosts.concat(posts);
        currentUrl = await page.evaluate(() => { const next = Array.from(document.querySelectorAll('a')).find(a => a.innerText.trim() === '>'); return next ? next.href : null; });
        if (currentUrl) { pageNum++; await DELAY(DELAY_BETWEEN_THREAD_PAGES); }
    }
    log(`  ✅ ${pageNum} pages, ${allPosts.length} posts`);
    return { posts: allPosts, pagesVisited: pageNum, pageUrls };
}

// ═══════════════════════════════════════════════════════════════════════════════
//  PER-CAR ORCHESTRATOR
// ═══════════════════════════════════════════════════════════════════════════════
async function processCar(page, carEntry, carIndex) {
    const { make, model, variant } = carEntry;
    const query      = `${make} ${model} ${variant}`;
    const slug       = query.replace(/\s+/g, '_').toLowerCase();
    const brandSlug  = make.toLowerCase();
    const modelSlug  = `${make}_${model}`.toLowerCase().replace(/\s+/g, '_');
    log(`\n${'═'.repeat(60)}\n🚗  CAR ${carIndex + 1}/${CAR_LIST.length}: ${query}\n${'═'.repeat(60)}`);

    let globalQueue = fs.existsSync(GLOBAL_QUEUE_FILE) ? JSON.parse(fs.readFileSync(GLOBAL_QUEUE_FILE, 'utf-8')) : {};
    let queueData = globalQueue[slug];

    const reviewLinks = await collectReviewLinks(page, query);
    if (!reviewLinks.length) { log('❌ No threads found — skipping car.'); return; }

    if (queueData) {
        log(`📋 Queue loaded for ${slug} (${queueData.threads.length} threads)`);
    } else {
        queueData = { query, scrapedAt: new Date().toISOString(), totalThreads: reviewLinks.length, threads: reviewLinks.map((url, i) => ({ index: i + 1, threadUrl: url, status: 'pending', pagesVisited: 0, pageUrls: [], postsScraped: 0 })) };
        globalQueue[slug] = queueData;
        fs.writeFileSync(GLOBAL_QUEUE_FILE, JSON.stringify(globalQueue, null, 2), 'utf-8');
    }

    let allThreadData = fs.existsSync(GLOBAL_REVIEWS_FILE) ? JSON.parse(fs.readFileSync(GLOBAL_REVIEWS_FILE, 'utf-8')) : [];
    let allMongoDocs  = fs.existsSync(GLOBAL_MONGO_FILE)   ? JSON.parse(fs.readFileSync(GLOBAL_MONGO_FILE,   'utf-8')) : [];

    for (let i = 0; i < queueData.threads.length; i++) {
        const entry = queueData.threads[i];
        if (entry.status === 'done') { log(`\n⏩ Thread ${i + 1} already done`); continue; }
        log(`\n${'─'.repeat(60)}\nThread ${i + 1}/${queueData.threads.length} — ${entry.threadUrl}`);
        try {
            const { posts, pagesVisited, pageUrls } = await scrapeThread(page, entry.threadUrl, async (pagePosts) => {
                pagePosts.forEach((post) => {
                    const doc = toMongoDoc({ post, threadUrl: entry.threadUrl, brandSlug, modelSlug, category: 'pending_ai', carEntry });
                    allMongoDocs.push(doc);
                });
            });
            entry.status = 'done'; entry.pagesVisited = pagesVisited; entry.pageUrls = pageUrls; entry.postsScraped = posts.length;
            if (posts.length > 0) {
                allThreadData.push({ threadUrl: entry.threadUrl, pagesVisited, posts });
            }
        } catch (err) { log(`⚠️  Error: ${err.message}`); entry.status = 'error'; entry.error = err.message; }

        fs.writeFileSync(GLOBAL_REVIEWS_FILE, JSON.stringify(allThreadData, null, 2), 'utf-8');
        globalQueue[slug] = queueData;
        fs.writeFileSync(GLOBAL_QUEUE_FILE,   JSON.stringify(globalQueue,     null, 2), 'utf-8');
        fs.writeFileSync(GLOBAL_MONGO_FILE,   JSON.stringify(allMongoDocs,  null, 2), 'utf-8');
        
        log(`💾 Saved — Thread ${i + 1}/${queueData.threads.length} done`);
        if (i < queueData.threads.length - 1) { await DELAY(DELAY_BETWEEN_THREADS); }
    }

    const totalPosts = allThreadData.reduce((s, t) => s + t.posts.length, 0);
    log(`\n🎉  Done!  Threads: ${allThreadData.length}  Posts: ${totalPosts}  Mongo: ${allMongoDocs.length}`);
}

// ═══════════════════════════════════════════════════════════════════════════════
//  MAIN
// ═══════════════════════════════════════════════════════════════════════════════
(async () => {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });

    // ── 1. Resume progress ────────────────────────────────────────────────────
    const progress  = loadProgress();
    const startFrom = progress.lastCompletedCarIndex + 1;
    log(`🚗  Cars to process : ${CAR_LIST.length}`);
    if (startFrom > 0) log(`⏩  Resuming from car ${startFrom + 1} (${CAR_LIST[startFrom]?.make} ${CAR_LIST[startFrom]?.model})`);

    // ── 2. Launch browser ─────────────────────────────────────────────────────
    const browser = await puppeteer.launch({ headless: false, defaultViewport: null, args: ['--no-sandbox', '--disable-setuid-sandbox', '--start-maximized'] });
    const page    = await browser.newPage();
    await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36');

    try {
        for (let i = startFrom; i < CAR_LIST.length; i++) {
            await processCar(page, CAR_LIST[i], i);
            saveProgress(i);
            log(`✅ Progress saved: car ${i + 1}/${CAR_LIST.length} done`);
            if (i < CAR_LIST.length - 1) { log(`Pausing ${DELAY_BETWEEN_CARS / 1000}s...`); await DELAY(DELAY_BETWEEN_CARS); }
        }

        log(`\n${'═'.repeat(60)}\n🏁  ALL CARS DONE!\n    Output: ${OUTPUT_DIR}`);
    } catch (err) {
        log(`❌ Fatal: ${err.message}`);
        console.error(err);
    } finally {
        log('\nBrowser left open.');
    }
})();